services:
  - type: web
    name: gcc-talent-marketplace-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES
        value: 30m
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES
        value: 7d
      - key: PLATFORM_FEE_PCT
        value: 10
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
